[program:queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasflimit=SIGTERM
stopwaitsecs=3600
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue-worker.log
stdout_logfile_maxbytes=10MB
stopasgroup=true
killasgroup=true
